#!/usr/bin/env python3
"""Prove-out driver: extract A-a Gradient from the PDF, harvest the mockup, diff.

This wires the whole pipeline end-to-end on the one calculator where both a PDF
and a mockup implementation exist, so the approach can be judged before the full
corpus is processed.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from extractor.diff import compare_metadata, run_differential
from extractor.pdf_extract import extract

ROOT = Path(__file__).parent
HTML = ROOT.parent / "inpharmd-clinical-calculators-mockup_15.html"

# Bridges the PDF's canonical field keys to the mockup's ad-hoc state prefixes.
# This is per-calculator glue; for the full corpus it is generated by matching
# labels, with only the ambiguous cases needing review.
FIELD_MAP = {
    "age": "age",
    "patient_temp": "temp",
    "elevation": "elev",
    "percent_inspired_o2": "fio2",
    "p_co2": "pco2",
    "resp_quot": "rq",
    "p_ao2": "pao2",
}
OUTPUT_MAP = {"expected_aag": "expectedMmhg", "measured_aag": "measuredMmhg"}

C = {
    "crit": "\033[91m", "high": "\033[93m", "med": "\033[96m",
    "ok": "\033[92m", "dim": "\033[90m", "b": "\033[1m", "r": "\033[0m",
}
BADGE = {
    "critical": f"{C['crit']}CRITICAL{C['r']}",
    "high": f"{C['high']}HIGH    {C['r']}",
    "medium": f"{C['med']}MEDIUM  {C['r']}",
    "low": f"{C['dim']}LOW     {C['r']}",
    "info": f"{C['dim']}INFO    {C['r']}",
}


def main() -> int:
    pdf_path = next((ROOT.parent / "source-pdfs").glob("*.pdf"))
    spec = extract(pdf_path)
    (ROOT / "out").mkdir(exist_ok=True)
    (ROOT / "out" / f"{spec['slug']}.pdf.json").write_text(
        json.dumps(spec, indent=2, ensure_ascii=False)
    )

    harvest = json.loads((ROOT / "out" / "html_harvest.json").read_text())
    entry = harvest["per_calculator"].get("pdf2")

    print(f"\n{C['b']}══ {spec['title']}  ({spec['slug']}){C['r']}")
    print(f"{C['dim']}   PDF  {pdf_path.name}  sha256:{spec['provenance']['source_sha256'][:16]}…{C['r']}")
    print(f"{C['dim']}   HTML mockup entry 'pdf2'{C['r']}\n")

    print(f"{C['b']}── Extracted from PDF ──{C['r']}")
    print(f"   {len(spec['inputs'])} inputs, {len(spec['compute']['steps'])} steps, "
          f"{len(spec['compute']['outputs'])} outputs, "
          f"{len(spec['info']['references'])} references")
    for o in spec["compute"]["outputs"]:
        print(f"   {C['ok']}{o['key']}{C['r']} = {o['expr']}")

    rep = compare_metadata(spec, entry, FIELD_MAP)
    print(f"\n{C['b']}── Metadata cross-check ──{C['r']}")
    if not rep.findings:
        print(f"   {C['ok']}no differences{C['r']}")
    for f in rep.sorted_findings():
        loc = f"{C['b']}{f.field}{C['r']}" if f.field else "-"
        print(f"   {BADGE[f.severity]} [{f.kind}] {loc}: {f.message}")

    print(f"\n{C['b']}── Differential test (200 random vectors) ──{C['r']}")
    d = run_differential(
        spec, HTML, "pdf2State", "calcPdf2", FIELD_MAP, OUTPUT_MAP, n=200
    )
    rep.differential = d
    if not d.get("ok"):
        print(f"   {C['crit']}harness failed{C['r']}: {d.get('error')}")
    else:
        verdict = (
            f"{C['ok']}IDENTICAL{C['r']}" if d["mismatch_count"] == 0
            else f"{C['crit']}{d['mismatch_count']} MISMATCHES{C['r']}"
        )
        print(f"   {d['comparisons']} output comparisons → {verdict}")
        print(f"   {C['dim']}agreement {d['agreement']}%  tol {d['tolerance']}  "
              f"pdf_eval_errors {d['pdf_eval_errors']}  html_nulls {d['html_null_results']}{C['r']}")
        for mm in d["mismatches"][:5]:
            print(f"   {C['crit']}·{C['r']} {mm['output']}: pdf={mm['pdf']} html={mm['html']} "
                  f"Δ={mm['abs_diff']:.6g}")

    (ROOT / "out" / f"{spec['slug']}.diff.json").write_text(
        json.dumps(
            {"slug": spec["slug"], "title": spec["title"],
             "findings": [f.as_dict() for f in rep.sorted_findings()],
             "differential": d},
            indent=2, ensure_ascii=False,
        )
    )
    print(f"\n{C['dim']}→ out/{spec['slug']}.pdf.json, out/{spec['slug']}.diff.json{C['r']}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
